/** Declaration file generated by dts-gen */
interface StrategyOptions {
    apiKeyField:string;
    apiSecretField:string;
    apiKeyHeader:string;
    apiSecretHeader:string;
    passReqToCallback:boolean;
}

interface VerifyPayload  {
    apiKey:string; 
    apiSecret:string;
}

export interface VerifiedCallback {
    (error: any, user?: any, info?: any): void;
}

export interface VerifyCallback {
    (payload: VerifyPayload, done: VerifiedCallback): void;
}

export interface VerifyCallbackWithRequest {
    (req: Request, payload: VerifyPayload, done: VerifiedCallback): void;
}

export class Strategy {
    constructor(options: StrategyOptions, verify: VerifyCallback);
    constructor(options: StrategyOptions, verify: VerifyCallbackWithRequest);
    authenticate(req: any, options: any): any;
    name: string;
}

export const version: string;

export function BadRequestError(message: any, ...args: any[]): void;

